name: "Security Tests"

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  security-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install SecTester dependencies
        run: npm install --save-dev @sectester/core @sectester/repeater @sectester/scan @sectester/runner

      - name: Start application using Docker Compose
        run: docker compose --file=compose.local.yml up -d --wait

      - name: Verify application readiness
        run: |
          for i in {1..10}; do
            nc -zv 127.0.0.1 3000 && echo "Application is ready" && exit 0
            echo "Waiting for application to be ready..."
            sleep 5
          done
          echo "Application failed to start in time" && exit 1

      - name: Configure Bright credentials
        uses: ./.github/workflows/composite/configure-bright-credentials
        with:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: 6tpzTWp4cY5Pr79dHAF3Zq
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}

      - name: Run security tests
        env:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: 6tpzTWp4cY5Pr79dHAF3Zq
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRIGHT_TOKEN: ${{ env.BRIGHT_TOKEN }}
          BRIGHT_TARGET_URL: http://127.0.0.1:3000
        run: |
          node --experimental-transform-types --experimental-strip-types --experimental-detect-module \
          --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning \
          --test-force-exit --test .brightsec/tests/*.test.ts --test-concurrency=4

      - name: Shutdown application
        if: always()
        run: docker compose --file=compose.local.yml down