name: Security Tests

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  security-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 18 for dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install application dependencies
        run: npm ci

      - name: Start application using Docker Compose
        run: |
          docker compose --file=compose.local.yml up -d --wait

      - name: Wait for application to be ready
        run: |
          until nc -zv 127.0.0.1 3000; do
            echo "Waiting for application to be ready..."
            sleep 5
          done

      - name: Set up Node.js 22 for SecTesterJS
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install SecTesterJS dependencies
        run: npm i --prefix .brightsec --save=false @sectester/core @sectester/repeater @sectester/scan @sectester/runner

      - name: Authenticate with Bright
        uses: ./.github/workflows/composite/configure-bright-credentials
        with:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: sLZMYVk98ogZGy8QvzNe5x
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}

      - name: Run security tests
        env:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: sLZMYVk98ogZGy8QvzNe5x
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRIGHT_TOKEN: ${{ env.BRIGHT_TOKEN }}
          BRIGHT_TARGET_URL: http://127.0.0.1:3000
        run: |
          node --experimental-transform-types --experimental-strip-types --experimental-detect-module \
          --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning \
          --test-force-exit --test .brightsec/tests/*.test.ts --test-concurrency=4

      - name: Shutdown application
        if: always()
        run: docker compose --file=compose.local.yml down