name: Bright

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install application dependencies
        run: npm ci --no-audit

      - name: Start application
        run: docker compose -f compose.local.yml up --wait
        env:
          KC_BOOTSTRAP_ADMIN_PASSWORD: Pa55w0rd
          KC_BOOTSTRAP_ADMIN_USERNAME: admin
          KC_DB: postgres
          KC_DB_PASSWORD: password
          KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
          KC_DB_USERNAME: keycloak
          POSTGRES_DB: bc
          POSTGRES_PASSWORD: bc
          POSTGRES_USER: bc

      - name: Wait for application to be ready
        run: |
          for i in {1..10}; do
            nc -zv 127.0.0.1 3000 && echo "Application is ready" && exit 0
            echo "Waiting for application..."
            sleep 5
          done
          echo "Application did not become ready in time" && exit 1

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install SecTesterJS dependencies
        run: npm i --save=false --prefix .brightsec @sectester/core @sectester/repeater @sectester/scan @sectester/runner @sectester/reporter

      - name: Configure Bright credentials
        uses: ./.github/workflows/composite/configure-bright-credentials
        with:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: kzDSPViNAfFv4AmWL4w3a1
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}

      - name: Run security tests
        run: node --experimental-transform-types --experimental-strip-types --experimental-detect-module --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning --test-force-exit --test-concurrency=4 --test .brightsec/tests/*.test.ts
        env:
          BRIGHT_HOSTNAME: development.playground.brightsec.com
          BRIGHT_PROJECT_ID: kzDSPViNAfFv4AmWL4w3a1
          BRIGHT_AUTH_ID: ${{ vars.BRIGHT_AUTH_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRIGHT_TOKEN: ${{ env.BRIGHT_TOKEN }}
          BRIGHT_TARGET_URL: http://127.0.0.1:3000
